BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.Broker SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
CREATE TABLE dbo.ContractsBroker
	(
	ID int NOT NULL,
	Created datetime NOT NULL,
	Updated datetime NOT NULL,
	Number nvarchar(50) NOT NULL,
	SubscriptionDate datetime NOT NULL,
	Status int NOT NULL,
	TerminationDate datetime NULL,
	BrokerID int NOT NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.ContractsBroker ADD CONSTRAINT
	PK_ContractsBroker PRIMARY KEY CLUSTERED 
	(
	ID
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.ContractsBroker ADD CONSTRAINT
	FK_ContractsBroker_Broker FOREIGN KEY
	(
	BrokerID
	) REFERENCES dbo.Broker
	(
	ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.ContractsBroker SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
GRANT SELECT, Update, delete , insert ON dbo.ContractsBroker TO Public 